update to version v2.2
- Fixed the call of a non-existent function within POSIXSDM (introduced in v2.1; "posixslm" to "sdmlogin")
- Changed the default directory for local user-dependant sxrc config files ($HOME/.config/sx/sxrc)
- Replaced all if-else statements with switch segments

diff --git a/POSIX Shell Login Manager/posixsdm b/POSIX Shell Login Manager/posixsdm
--- a/POSIX Shell Login Manager/posixsdm
+++ b/POSIX Shell Login Manager/posixsdm
@@ -13,7 +13,7 @@ read -r tel
 		[Ee]) printf "\nExiting to TTY login...\n"
 		exit 0;;
 		[Ll]) printf "\nReturning to login screen...\n"
-		slmlogin;;
+		sdmlogin;;
 		*) printf "\nError: illegal input\n"
 	esac
 done
@@ -32,7 +32,7 @@ case "$wcheck" in
 	exec dbus-launch --exit-with-session $runwm;;
 	0) printf "\!!!CRITICAL ERROR!!!\n\nNo Wayland-based window manager or desktop environment found\nPress any key to go back to the start menu "
 	read az
-	posixslm
+	sdmlogin
 esac
 
 while true; do
@@ -65,9 +65,9 @@ case "$xcheck" in
 	1) printf "\nOnly one environment found, running\n"
 	runwm=$(sed -n 's/^Exec=//p' $xses/*.desktop)
 	exec dbus-launch --exit-with-session $runwm;;
-	0) printf "\!!!CRITICAL ERROR!!!\n\nNo Xorg-based window manager or desktop environment found\nPress any key to go back to the start menu "
+	0) printf "\n!!!CRITICAL ERROR!!!\n\nNo Xorg-based window manager or desktop environment found\nPress any key to go back to the start menu "
 	read az
-	posixslm
+	sdmlogin
 esac
 
 while true; do
@@ -81,21 +81,23 @@ read -r wm
 		$wm) [ -f $xses/$wm.desktop ]
 		case $? in
 			0) runwm=$(sed -n 's/^Exec=//p' $xses/$wm.desktop)
-			if [ -f /usr/bin/sx ]; then
-				exec dbus-launch --exit-with-session sx $runwm
-			elif [ -f /usr/bin/startx ]; then
-				exec dbus-launch --exit-with-session startx $runwm
-			else
-				printf "\!!!CRITICAL ERROR!!!\n\nXorg cannot be run, as startx and sx cannot be found\n"
-			fi;;
-			*) printf "\nError: illegal input or .desktop file not found\n"
+			[ -f /usr/bin/sx ]
+			case $? in
+				0) exec dbus-launch --exit-with-session sx $runwm;;
+				*) [ -f /usr/bin/startx ]
+				case $? in
+					0) exec dbus-launch --exit-with-session startx $runwm;;
+					*) printf "\n!!!CRITICAL ERROR!!!\n\nXorg cannot be run, as startx and sx cannot be found\n"
+				esac;;
+			*) printf "\nError: illegal input or .desktop file not found\n";;
+			esac
 		esac
 	esac
 done
 }
 
 # Interactive console-based menu to navigate through all options presented in this script
-slmlogin() {
+sdmlogin() {
 clear
 printf "POSIX Shell Display Manager\n\n"
 w
@@ -128,7 +130,7 @@ printf "WARNING: TTY1 was not detected.\nIt is not recommended to run a desktop 
 printf "Do you want to continue? (Y/N) "
 read -r yn
 	case $yn in
-		[Yy]) slmlogin;;
+		[Yy]) sdmlogin;;
 		[Nn]) ttyexit;;
 		*) printf "\nError: illegal input\n"
 	esac
@@ -173,8 +175,8 @@ wses=/usr/share/wayland-sessions
 opt="-r, -h, -x, -w"
 
 case $1 in
-	-r|--run) concheck && slmlogin
-	warning;;
+	-r|--run) concheck
+	sdmlogin;;
 	-h|--help) printf "Terminal-based display manager written in POSIX Shell\n"
 	printf "Usage: posixsdm <option> [...]\nOptions:"
 	printf "\n-r, --run\tRun the script and do a variable check"
