bump to version v3.2
changes too big to include, check CHANGELOG

diff --git a/POSIXSDM/posixsdm b/POSIXSDM/posixsdm
--- a/POSIXSDM/posixsdm
+++ b/POSIXSDM/posixsdm
@@ -1,21 +1,20 @@
 #!/bin/sh
-# posixsdm - Terminal-based display manager
+## posixsdm - TTY-based display manager
 
 ttyexit() {
 # Return to TTY or the start of the script
 printf "\nEntered exit prompt\n"
-while true; do
-printf "Do you want to return to the TTY, exit or go to the login menu? (T/E/L) "
-read -r tel
-	case "$tel" in
+while read -rp "Do you want to return to the TTY, exit or go to the login menu? ([T]TY/E[x]it/[L]ogin) " txl; do
+	case "$txl" in
 		[Tt]) printf "\nExiting to TTY shell...\n"
 		exec "$SHELL";;
-		[Ee]) printf "\nExiting to TTY login...\n"
+		[Xx]) printf "\nExiting to TTY login...\n"
 		exit 0;;
 		[Ll]) printf "\nReturning to posixsdm login...\n"
 		case "$tty_warn" in
-			"") concheck;;
-			*) warning
+			1) run_once=1
+			warn_user;;
+			"") concheck
 		esac;;
 		*) printf "\nError: invalid input\n\n"
 	esac
@@ -24,17 +23,13 @@ done
 
 wrun() {
 # xrun() equivalent for Wayland
-if [ -f "$wses"/$wm.desktop ] || [ "$wcheck" -eq 1 ]; then
+if [ -f "$wses"/$wm.desktop ]; then
 	export XDG_SESSION_TYPE="wayland"
 	printf "\nRunning %s\n" "$runwm"
-	exec "$runwm"
-elif [ "$wcheck" -eq 0 ]; then
-	printf "\n\n%sCRITICAL ERROR%s\nNo Wayland-based environment has been found.\nPress any key to go back to the start menu" "${RED}" "${NORMAL}"
-	read -r az
-	sdmlogin
+	$dexec "$runwm" $param
 else
-	printf "\nError: invalid input or .desktop file not found\n"
 	export XDG_SESSION_TYPE="tty"
+	printf "\nError: invalid input or .desktop file not found\n"
 fi
 }
 
@@ -43,24 +38,17 @@ xrun() {
 # If sx is found, execute Xorg via sx. Otherwise, use startx
 # Read input to search for xsessions .desktop files
 # Finally: if nothing is found, warn user
-if [ -f "$xses"/$wm.desktop ] || [ "$xcheck" -eq 1 ]; then
+if [ -f "$xses"/$wm.desktop ]; then
 	export XDG_SESSION_TYPE="x11"
+	[ -f /usr/bin/startx ] && xstart="startx" || [ -f /usr/bin/sx ] && xstart="sx"
 	printf "\nRunning %s\n" "$runwm"
-	if [ -f /usr/bin/startx ]; then
-		exec dbus-launch --exit-with-session startx "$runwm"
-	elif [ -f /usr/bin/sx ]; then
-		exec dbus-launch --exit-with-session sx "$runwm"
-	elif [ -f "$minisx" ]; then
-		exec dbus-launch --exit-with-session "$minisx" "$runwm"
-	else
-		export XDG_SESSION_TYPE="tty"
-		printf "\n\n%sCRITICAL ERROR%s\nXorg cannot be run: startx and sx cannot be found\n" "${RED}" "${NORMAL}"
-	fi
-elif [ "$xcheck" -eq 0 ]; then
-	printf "\n\n%sCRITICAL ERROR%s\nNo Xorg-based environment has been found.\nPress any key to go back to the start menu" "${RED}" "${NORMAL}"
-	read -r az
-	sdmlogin
+	$dexec $xstart "$runwm" $param
+elif [ ! -f /usr/bin/sx ] && [ ! -f /usr/bin/startx ]; then
+	printf "\n\n%sCRITICAL ERROR%s\nXorg cannot be run:
+startx and sx cannot be found
+Please install startx or sx to fix this issue.\n" "$RED" "$NORMAL"
 else
+	export XDG_SESSION_TYPE="tty"
 	printf "\nError: invalid input or .desktop file not found\n"
 fi
 }
@@ -69,22 +57,19 @@ wsetup() {
 printf "\nEntered Wayland prompt\n"
 wcheck=$(find "$wses" -type f | wc -l)
 case "$wcheck" in
-	1) runwm=$(sed -n 's/^Exec=//p' "$wses"/*.desktop)
-	printf "\nOnly one environment found"
+	1) printf "\nOnly one environment found"
+	runwm=$(grep -oP '(?<=Exec= ).*' "$wses"/*.desktop)
 	wrun;;
-	0) printf "%sCRITICAL ERROR%s" "${RED}" "${NORMAL}"
-	printf "No Wayland-based environment found\nPress any key to go back to the start menu "
-	read -r az
+	0) printf "\n%sCRITICAL ERROR%s\nNo Wayland-based environment has been found." "$RED" "$NORMAL"
+	read -rp "Press return to go back to the start menu " az
 	sdmlogin
 esac
 
-while true; do
-printf "\nWhat Wayland desktop do you want to run?\n\nOptions:\nView .desktop files, Exit, Run Desktop (V/X/INPUT) "
-read -r wm
+while read -rp "What Wayland desktop do you want to run? ([V]iew/E[x]it/[INPUT]) " wm; do
 	case "$wm" in
 		[Vv]) find "$wses" -type f -printf "%f\n";;
 		[Xx]) ttyexit;;
-		"$wm") runwm=$(sed -n 's/^Exec=//p' "$wses"/$wm.desktop)
+		*) runwm=$(grep -oP '(?<=Exec=).*' "$wses"/$wm.desktop) param="$2"
 		wrun
 	esac
 done
@@ -94,23 +79,19 @@ xsetup() {
 printf "\nEntered X.Org prompt\n"
 xcheck=$(find "$xses" -type f | wc -l)
 case "$xcheck" in
-	1) runwm=$(sed -n 's/^Exec=//p' "$xses"/*.desktop)
-	printf "\nOnly one environment found"
+	1) printf "\nOnly one environment found\n"
+	runwm=$(grep -oP '(?<=Exec=).*' "$xses"/*.desktop)
 	xrun;;
-	0) printf "%sCRITICAL ERROR%s\nNo Xorg-based environment found\n" "${RED}" "${NORMAL}"
-	printf "Press any key to go back to the start menu "
-	read -r az
+	0) printf "\n%sCRITICAL ERROR%s\nNo Xorg-based environment has been found.\n" "$RED" "$NORMAL"
+	read -rp "Press return to go back to the start menu " az
 	sdmlogin
 esac
 
-while true; do
-printf "\nWhat X.Org desktop do you want to start?\n\n"
-printf "Options:\nView .desktop files, Exit, Run Desktop (V/X/INPUT) "
-read -r wm
+while read -rp "What X.Org desktop do you want to start? ([V]iew/E[x]it/[INPUT]) " wm; do
 	case "$wm" in
 		[Vv]) find "$xses" -type f -printf "%f\n";;
 		[Xx]) ttyexit;;
-		"$wm") runwm=$(sed -n 's/^Exec=//p' "$xses"/$wm.desktop)
+		*) runwm=$(grep -oP '(?<=Exec=).*' "$xses"/$wm.desktop) param="$2"
 		xrun
 	esac
 done
@@ -125,29 +106,31 @@ printf "\nRecent logins:\n\n"
 last | head -n 6
 printf "\nCurrently used shell: %s\n\nInstalled desktops:\n\n" "$SHELL"
 find "$xses" "$wses" -type f
-printf "\n%sNOTE: Only .desktop files that exist can be run.%s\n\n" "${YELLOW}" "${NORMAL}"
+printf "\n%sNOTE: Only .desktop files that exist can be run.%s\n\n" "$YELLOW" "$NORMAL"
 
-while true; do
-printf "Do you want to run an X.Org or Wayland desktop? (X/W/N) "
-read -r xwn
-	case "$xwn" in
+while read -rp "Do you want to run an X.Org or Wayland desktop? ([X]org/[W]ayland/[E]xit) " xwe; do
+	case "$xwe" in
 		[Xx]) xsetup;;
 		[Ww]) wsetup;;
-		[Nn]) ttyexit;;
+		[Ee]) ttyexit;;
 		*) printf "\nError: invalid input\n\n"
 	esac
 done
 }
 
-warning() {
+warn_user() {
 # If a desktop is detected or TTY isn't running, warn user
+[ "$runner" ] && if ! [ -f "$wses"/$wm ] && ! [ -f "$xses"/$wm ]; then
+	empty_runner="The specified desktop doesn't exist, and "
+fi
+
 while true; do
-printf "%sWARNING: TTY1 was not detected or a desktop is running.%s\nDo you want to continue? (Y/N) " "${YELLOW}" "${NORMAL}"
-read -r yn
+	printf "%sWARNING: %sTTY1 was not detected or a desktop is running.%s\n" "$YELLOW" "$empty_runner" "$NORMAL"
+	read -rp "Do you want to continue? (Y/N) " yn
 	case "$yn" in
 		[Yy]) case "$wm" in
 			"") sdmlogin;;
-			*) "$runner"
+			*) [ "$run_once" ] && sdmlogin || "$runner"
 		esac;;
 		[Nn]) ttyexit;;
 		*) printf "\nError: invalid input\n\n"
@@ -156,40 +139,38 @@ done
 }
 
 concheck() {
-# See if ${DISPLAY} is empty and TTY1 is detected, then view $wm and run $runner
-# If the conditions are not met, enter warning prompt
-if [ -z "${DISPLAY}" ] && [ "${XDG_VTNR}" -eq 1 ]; then
+# See if $DISPLAY is empty and TTY1 is detected, then view $wm and run $runner
+# If the conditions are not met, enter warn_user prompt
+if [ -z "$DISPLAY" ] && [ "$XDG_VTNR" -eq 1 ]; then
 	case "$wm" in
 		"") sdmlogin;;
 		*) "$runner"
 	esac
 else
 	tty_warn=1
-	warning
+	warn_user
 fi
 }
 
 # Set variables and parameters for switch statement to handle user input
 # Call concheck() and continue from there
-xses="/usr/share/xsessions"
-wses="/usr/share/wayland-sessions"
-minisx="$HOME/.config/posixsdm/sx"
-YELLOW=$(tput setaf 3)
-RED=$(tput setaf 1)
-NORMAL=$(tput sgr0)
+xses="/usr/share/xsessions" wses="/usr/share/wayland-sessions"
+YELLOW=$(tput setaf 3) RED=$(tput setaf 1) NORMAL=$(tput sgr0)
+wm="$2" param="$3" name="posixsdm"
+[ -z "$param" ] && dexec="exec dbus-run-session"
 
 case "$1" in
-	-r|--run) concheck;;
-	-x|--xorg) wm="$2" runner=xrun runwm=$(sed -n 's/^Exec=//p' "$xses"/$wm.desktop)
-	concheck;;
-	-w|--wayland) wm="$2" runner=wrun runwm=$(sed -n 's/^Exec=//p' "$wses"/$wm.desktop)
-	concheck;;
-	-h|--help) printf "Terminal-based display manager written in POSIX Shell\n"
-	printf "Usage: posixsdm <option> [...]\n\nOptions:\n"
-	printf -- "-r, --run\t\tRun the script and do a variable check\n"
-	printf -- "-x, --xorg [INPUT] \tRun Xorg-based desktop directly (not recommended)\n"
-	printf -- "-w, --wayland [INPUT]\tRun wayland-based desktop directly (not recommended)\n"
-	printf -- "-h, --help\t\tDisplay this help message\n";;
-	"") printf "Error: whitespace detected\nUsage: posixsdm <option> [...]\nOptions: --help, --run, --wayland, --xorg\n";;
-	*) printf "Error: '%s' is not a valid option\nUsage: posixsdm <option> [...]\nOptions: --help, --run, --wayland, --xorg\n" "$1"
+	-[Rr]|--run) break;;
+	-[Xx]|--xorg) runner=xrun runwm=$(grep -oP '(?<=Exec=).*' "$xses"/$wm.desktop);;
+	-[Ww]|--wayland) runner=wrun runwm=$(grep -oP '(?<=Exec=).*' "$wses"/$wm.desktop);;
+	-[Hh]|--help) printf "TTY-based display manager written in modern POSIX-compliant Shell
+Usage: %s <option> [...]\n\nOptions:\n-r, --run\t\tRun the script and do a variable check
+-x, --xorg [INPUT] \tRun Xorg-based desktop directly (not recommended)
+-w, --wayland [INPUT]\tRun wayland-based desktop directly (not recommended)
+-h, --help\t\tDisplay this help message\n" "$name"; exit;;
+	"") printf "Error: whitespace detected\nUsage: %s <option> [...]
+Options: --help, --run, --wayland, --xorg\n" "$name"; exit;;
+	*) printf "Error: %s is not a valid option\nUsage: %s <option> [...]
+Options: --help, --run, --wayland, --xorg\n" "$1" "$name"; exit
 esac
+concheck
