setup: Allow user to specify account to install POSIXSDM to
- Removed sdm_setup() for sdm_check_user()
This should allow the user to specify an account to install POSIXSDM to
at login
- Set the .profile based on user's /etc/passwd shell instead of user's
input
- Minor cleanup (formatting)

diff --git a/src/setup b/src/setup
--- a/src/setup
+++ b/src/setup
@@ -4,8 +4,8 @@
 sdm_uninstall() {
 	printf "Removing POSIXSDM and associated files...\n"
 	[ -f /usr/bin/posixsdm ] && sudo rm /usr/bin/posixsdm
-	[ -d "$HOME"/.config/posixsdm ] && rm -r "$HOME"/.config/posixsdm
-	sed -i '/posixsdm/d' "$HOME"/.*profile
+	[ -d "$user_directory"/.config/posixsdm ] && rm -r "$user_directory"/.config/posixsdm
+	sed -i '/posixsdm/d' "$conf"
 	printf "POSIXSDM has been removed.\n\n"
 
 	while read -rp "The script has finished. Do you want to reboot the machine? ([Y]es/[N]o) " yn; do
@@ -23,15 +23,16 @@ sdm_uninstall() {
 }
 
 sdm_install() {
+	printf "\n%s detected for user %s, installing via %s file.\n" "$shell_profile" "$specify_user" "$conf"
 	while read -rp "Do you want to install POSIXSDM locally or globally? ([U]ser|RETURN/[R]oot) " priv; do
 		case "$priv" in
 		user | u | "")
 			printf "Installing locally\n"
 			dir="/.config/posixsdm/"
-			mkdir "$HOME"/.config/posixsdm/
+			mkdir "$user_directory"/.config/posixsdm/
 			chmod +x ./posixsdm
-			cp ./posixsdm "$HOME"/.config/posixsdm/
-			chmod +x "$HOME"/.config/posixsdm/
+			cp ./posixsdm "$user_directory"/.config/posixsdm/
+			chmod +x "$user_directory"/.config/posixsdm/
 			break
 			;;
 		root | r)
@@ -59,7 +60,7 @@ sdm_install() {
 				wm_full=$(find /usr/share/*sessions/$wm_input.desktop -type f -exec basename {} .desktop \;)
 				runwm=$(grep -oP '(?<=Exec=).*' /usr/share/*sessions/"$wm_full".desktop | head -1)
 				if [ -f /usr/bin/"$runwm" ]; then
-					printf "exec %s%sposixsdm -w %s" "$HOME" "$dir" "$wm_full" >>"$conf"
+					printf "exec %s%sposixsdm -w %s" "$user_directory" "$dir" "$wm_full" >>"$conf"
 					break 2
 				else
 					printf "Error: input is invalid or desktop doesn't exist\n"
@@ -68,7 +69,7 @@ sdm_install() {
 			;;
 		[Nn])
 			printf "Running posixsdm in standard mode\n"
-			printf "exec %s%sposixsdm -r" "$HOME" "$dir" >>"$conf"
+			printf "exec %s%sposixsdm -r" "$user_directory" "$dir" >>"$conf"
 			break
 			;;
 		*)
@@ -92,42 +93,60 @@ Please uninstall your current display manager and reboot your machine to run POS
 	done
 }
 
-sdm_setup() {
-	while read -rp "Is your login shell ZSH, Bash or POSIX SH? ([Z]SH/[P]OSIXSH/E[x]it) " zpx; do
-		case "$zpx" in
-		[Zz])
-			conf="$HOME/.zprofile"
-			break
-			;;
-		[Pp])
-			conf="$HOME/.profile"
-			break
-			;;
-		[Xx])
-			printf "Exiting.\n"
-			exit 3
+sdm_check_user() {
+	while read -rp "What user do you want to run this script for? ([C]urrent|RETURN/[INPUT]) " specify_user; do
+		case "$specify_user" in
+		[Cc] | "")
+			specify_user="$USER"
+			user_directory=/home/"$USER"
 			;;
 		*)
-			printf "\nIncorrect input detected, repeating prompt...\n"
+			user_directory=/home/"$specify_user"
 			;;
 		esac
+
+		if ! find "$user_directory" -maxdepth 1 -type d | head -n1; then
+			user_not_found=1
+		fi
+
+		shell_profile=$(grep ^"$specify_user": /etc/passwd | cut -f 7 -d :)
+
+		if [ -z "$user_not_found" ]; then
+			case "$shell_profile" in
+			"/bin/sh" | "/usr/bin/sh")
+				conf="$user_directory"/.profile
+				break
+				;;
+			"/bin/bash" | "/usr/bin/bash")
+				conf="$user_directory"/.bash_profile
+				break
+				;;
+			"/bin/zsh" | "/usr/bin/zsh")
+				conf="$user_directory"/.zprofile
+				break
+				;;
+			*)
+				printf "Error: shell is not compatible\n"
+				;;
+			esac
+		else
+			printf "Error: user not found\n"
+		fi
 	done
-	printf "\nInstalling via %s file.\n" "$conf"
-	sdm_install
 }
 
 sdm_prompt() {
 	while :; do
-		printf "POSIXSDM Setup Script \
-		\nPlease read the README file for more information before installation\n"
 		read -rp "Do you want to install or uninstall POSIXSDM? ([I]nstall/[U]ninstall/E[x]it) " iux
 		case "$iux" in
 		[Ii])
 			printf "\nStarting installation setup.\n"
+			sdm_check_user
 			sdm_setup
 			;;
 		[Uu])
 			printf "\nStarting uninstall setup.\n"
+			sdm_check_user
 			sdm_uninstall
 			;;
 		[Xx])
@@ -141,21 +160,19 @@ sdm_prompt() {
 	done
 }
 
+printf "POSIXSDM Setup Script\nPlease read the README file for more information before installation\n"
+
 case "$1" in
--i | --install) sdm_setup ;;
--is | --install-sh)
-	printf "\nSelected BASH/POSIX Shell setup\n"
-	conf="$HOME/.profile"
+-i | --install)
+	sdm_check_user
+	sdm_install
 	;;
--iz | --install-zsh)
-	printf "Selected ZSH setup\n"
-	conf="$HOME/.zprofile"
+-u | --uninstall)
+	sdm_check_user
+	sdm_uninstall
 	;;
--u | --uninstall) sdm_uninstall ;;
 -h | --help) printf "POSIXSDM setup script \
 	\nUsage: setup <option> [...]\n\nOptions:\n-i, --install\t\tRun the installer \
-	\n-iz, --install-zsh\tInstall for ZSH Shell \
-	\n-is, --install-sh\tInstall for BASH/POSIX Shell \
 	\n-u, --uninstall\t\tRun the uninstaller \
 	\n-h, --help\t\tDisplay this help message\n" ;;
 "")
